import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'IQRA',
//   description: 'Education App',
// }

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <head>
        <title>IQRA Education App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
